<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Perkara;
use App\Models\Personel;
use App\Models\Kategori;
use App\Models\User;
use Carbon\Carbon;

class CompletePerkaraSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::all();
        $kategoris = Kategori::all();
        $personels = Personel::all();

        if ($users->isEmpty() || $kategoris->isEmpty()) {
            $this->command->warn('Please run UserSeeder and KategoriSeeder first!');
            return;
        }

        $perkaras = [
            [
                'nomor_perkara' => 'PKR/001/DIV-2/XII/2024',
                'jenis_perkara' => 'Pelanggaran Disiplin',
                'nama' => 'Kasus Terlambat Apel',
                'deskripsi' => 'Anggota terlambat mengikuti apel pagi tanpa izin yang sah selama 3 hari berturut-turut',
                'kategori_id' => $kategoris->where('nama', 'Disiplin')->first()->id ?? 1,
                'tanggal_masuk' => Carbon::now()->subDays(45),
                'tanggal_perkara' => Carbon::now()->subDays(50),
                'tanggal_selesai' => Carbon::now()->subDays(15),
                'tanggal_pendaftaran' => Carbon::now()->subDays(46),
                'klasifikasi_perkara' => 'Ringan',
                'status' => 'Selesai',
                'priority' => 'Low',
                'progress' => 100,
                'oditur' => json_encode(['Mayor Andi Wijaya']),
                'terdakwa' => json_encode(['Prada Muhammad Rizki']),
                'pasal_dakwaan' => 'Pasal 7 ayat 1 UU Disiplin Prajurit TNI',
                'tanggal_kejadian' => Carbon::now()->subDays(52),
                'tempat_kejadian' => 'Lapangan Apel Yonif 1 Kostrad',
                'keterangan' => 'Perkara telah diselesaikan dengan sanksi teguran tertulis',
                'is_public' => true,
                'assigned_to' => $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/002/DIV-2/XII/2024',
                'jenis_perkara' => 'Tindak Pidana',
                'nama' => 'Kasus Pencurian Senjata',
                'deskripsi' => 'Dugaan pencurian 2 pucuk senjata laras panjang dari gudang persenjataan',
                'kategori_id' => $kategoris->where('nama', 'Pidana')->first()->id ?? 3,
                'tanggal_masuk' => Carbon::now()->subDays(30),
                'tanggal_perkara' => Carbon::now()->subDays(35),
                'tanggal_pendaftaran' => Carbon::now()->subDays(31),
                'klasifikasi_perkara' => 'Berat',
                'status' => 'Proses',
                'priority' => 'High',
                'deadline' => Carbon::now()->addDays(30),
                'progress' => 60,
                'oditur' => json_encode(['Letkol Budi Santoso', 'Mayor Chandra Kusuma']),
                'terdakwa' => json_encode(['Serda Indra Mahendra']),
                'pasal_dakwaan' => 'Pasal 363 KUHP tentang Pencurian dalam Keadaan Memberatkan',
                'nomor_surat_pelimpahan' => 'SP/045/DIV-2/XII/2024',
                'tanggal_surat_pelimpahan' => Carbon::now()->subDays(28),
                'nomor_bap_penyidik' => 'BAP/032/POM/XII/2024',
                'tanggal_bap_penyidik' => Carbon::now()->subDays(33),
                'tanggal_kejadian' => Carbon::now()->subDays(40),
                'tempat_kejadian' => 'Gudang Senjata Yonif 5 Kostrad',
                'keterangan' => 'Perkara masih dalam tahap pemeriksaan saksi',
                'internal_notes' => 'Perlu koordinasi dengan Pomdam',
                'tags' => json_encode(['urgent', 'pidana-berat', 'senjata']),
                'is_public' => false,
                'assigned_to' => $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/003/DIV-2/XII/2024',
                'jenis_perkara' => 'Administrasi',
                'nama' => 'Keterlambatan Laporan Keuangan',
                'deskripsi' => 'Keterlambatan penyampaian laporan pertanggungjawaban keuangan unit',
                'kategori_id' => $kategoris->where('nama', 'Administrasi')->first()->id ?? 2,
                'tanggal_masuk' => Carbon::now()->subDays(20),
                'tanggal_perkara' => Carbon::now()->subDays(25),
                'tanggal_pendaftaran' => Carbon::now()->subDays(21),
                'klasifikasi_perkara' => 'Sedang',
                'status' => 'Proses',
                'priority' => 'Medium',
                'deadline' => Carbon::now()->addDays(15),
                'progress' => 40,
                'oditur' => json_encode(['Kapten Dedi Prasetyo']),
                'terdakwa' => json_encode(['Kopka Joko Widodo']),
                'pasal_dakwaan' => 'Pasal 15 UU Disiplin Prajurit TNI tentang Kelalaian Tugas',
                'tanggal_kejadian' => Carbon::now()->subDays(30),
                'tempat_kejadian' => 'Kantor Keuangan Yonif 2 Kostrad',
                'keterangan' => 'Masih dalam proses klarifikasi dokumen',
                'is_public' => true,
                'assigned_to' => $users->count() > 1 ? $users->skip(1)->first()->id : $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/004/DIV-2/XII/2024',
                'jenis_perkara' => 'Pelanggaran Disiplin',
                'nama' => 'Absen Tanpa Izin (AWOL)',
                'deskripsi' => 'Anggota tidak hadir di kesatuan selama 5 hari tanpa izin yang sah',
                'kategori_id' => $kategoris->where('nama', 'Disiplin')->first()->id ?? 1,
                'tanggal_masuk' => Carbon::now()->subDays(10),
                'tanggal_perkara' => Carbon::now()->subDays(15),
                'tanggal_pendaftaran' => Carbon::now()->subDays(11),
                'klasifikasi_perkara' => 'Sedang',
                'status' => 'Proses',
                'priority' => 'Medium',
                'deadline' => Carbon::now()->addDays(20),
                'progress' => 30,
                'oditur' => json_encode(['Lettu Eko Wahyudi']),
                'terdakwa' => json_encode(['Pratu Nur Hidayat']),
                'pasal_dakwaan' => 'Pasal 8 UU Disiplin Prajurit TNI',
                'tanggal_kejadian' => Carbon::now()->subDays(20),
                'tempat_kejadian' => 'Yonkav Kostrad',
                'keterangan' => 'Terdakwa dalam proses pemeriksaan',
                'is_public' => true,
                'assigned_to' => $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/005/DIV-2/XI/2024',
                'jenis_perkara' => 'Tindak Pidana',
                'nama' => 'Kasus Penganiayaan',
                'deskripsi' => 'Dugaan penganiayaan terhadap sesama anggota menyebabkan luka berat',
                'kategori_id' => $kategoris->where('nama', 'Pidana')->first()->id ?? 3,
                'tanggal_masuk' => Carbon::now()->subDays(60),
                'tanggal_perkara' => Carbon::now()->subDays(65),
                'tanggal_selesai' => Carbon::now()->subDays(5),
                'tanggal_pendaftaran' => Carbon::now()->subDays(61),
                'klasifikasi_perkara' => 'Berat',
                'status' => 'Selesai',
                'priority' => 'High',
                'progress' => 100,
                'oditur' => json_encode(['Mayor Chandra Kusuma', 'Kapten Dedi Prasetyo']),
                'terdakwa' => json_encode(['Serka Gunawan Hidayat']),
                'pasal_dakwaan' => 'Pasal 351 ayat 2 KUHP tentang Penganiayaan Berat',
                'nomor_surat_pelimpahan' => 'SP/038/DIV-2/XI/2024',
                'tanggal_surat_pelimpahan' => Carbon::now()->subDays(58),
                'nomor_surat_dakwaan' => 'SD/012/DIV-2/XI/2024',
                'tanggal_surat_dakwaan' => Carbon::now()->subDays(40),
                'nomor_skeppera' => 'SKEP/008/DIV-2/XI/2024',
                'tanggal_skeppera' => Carbon::now()->subDays(10),
                'pejabat_skeppera' => 'Komandan Divisi 2 Kostrad',
                'nomor_bap_penyidik' => 'BAP/025/POM/XI/2024',
                'tanggal_bap_penyidik' => Carbon::now()->subDays(63),
                'tanggal_kejadian' => Carbon::now()->subDays(70),
                'tempat_kejadian' => 'Mess Prajurit Yonif 4 Kostrad',
                'keterangan' => 'Terdakwa divonis hukuman disiplin berat dan penurunan pangkat',
                'tags' => json_encode(['pidana', 'penganiayaan', 'selesai']),
                'is_public' => false,
                'assigned_to' => $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/006/DIV-2/XII/2024',
                'jenis_perkara' => 'Administrasi',
                'nama' => 'Kehilangan Dokumen Rahasia',
                'deskripsi' => 'Kehilangan dokumen rahasia operasi militer dari filing kabinet',
                'kategori_id' => $kategoris->where('nama', 'Administrasi')->first()->id ?? 2,
                'tanggal_masuk' => Carbon::now()->subDays(8),
                'tanggal_perkara' => Carbon::now()->subDays(10),
                'tanggal_pendaftaran' => Carbon::now()->subDays(9),
                'klasifikasi_perkara' => 'Berat',
                'status' => 'Proses',
                'priority' => 'Urgent',
                'deadline' => Carbon::now()->addDays(10),
                'progress' => 25,
                'oditur' => json_encode(['Letkol Budi Santoso']),
                'terdakwa' => json_encode(['Koptu Kurniawan Setiawan']),
                'pasal_dakwaan' => 'Pasal 16 UU Rahasia Negara tentang Kelalaian Pengamanan Dokumen',
                'tanggal_kejadian' => Carbon::now()->subDays(12),
                'tempat_kejadian' => 'Kantor Intel Yonbekang Kostrad',
                'keterangan' => 'Masih dalam tahap investigasi awal',
                'internal_notes' => 'URGENT - Dokumen mengandung informasi sensitif',
                'tags' => json_encode(['urgent', 'rahasia', 'kehilangan-dokumen']),
                'is_public' => false,
                'assigned_to' => $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/007/DIV-2/XII/2024',
                'jenis_perkara' => 'Pelanggaran Disiplin',
                'nama' => 'Penyalahgunaan Fasilitas Dinas',
                'deskripsi' => 'Penggunaan kendaraan dinas untuk keperluan pribadi tanpa izin',
                'kategori_id' => $kategoris->where('nama', 'Disiplin')->first()->id ?? 1,
                'tanggal_masuk' => Carbon::now()->subDays(5),
                'tanggal_perkara' => Carbon::now()->subDays(7),
                'tanggal_pendaftaran' => Carbon::now()->subDays(6),
                'klasifikasi_perkara' => 'Ringan',
                'status' => 'Proses',
                'priority' => 'Low',
                'deadline' => Carbon::now()->addDays(25),
                'progress' => 15,
                'oditur' => json_encode(['Letda Fajar Nugroho']),
                'terdakwa' => json_encode(['Kopda Lukman Hakim']),
                'pasal_dakwaan' => 'Pasal 12 UU Disiplin Prajurit TNI',
                'tanggal_kejadian' => Carbon::now()->subDays(10),
                'tempat_kejadian' => 'Pool Kendaraan Yonbekang Kostrad',
                'keterangan' => 'Proses pemeriksaan awal',
                'is_public' => true,
                'assigned_to' => $users->count() > 1 ? $users->skip(1)->first()->id : $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/008/DIV-2/XII/2024',
                'jenis_perkara' => 'Tindak Pidana',
                'nama' => 'Kasus Desersi',
                'deskripsi' => 'Anggota meninggalkan kesatuan tanpa izin lebih dari 30 hari',
                'kategori_id' => $kategoris->where('nama', 'Pidana')->first()->id ?? 3,
                'tanggal_masuk' => Carbon::now()->subDays(3),
                'tanggal_perkara' => Carbon::now()->subDays(35),
                'tanggal_pendaftaran' => Carbon::now()->subDays(4),
                'klasifikasi_perkara' => 'Berat',
                'status' => 'Proses',
                'priority' => 'Urgent',
                'deadline' => Carbon::now()->addDays(60),
                'progress' => 10,
                'oditur' => json_encode(['Mayor Andi Wijaya']),
                'terdakwa' => json_encode(['Praka Oki Permana']),
                'pasal_dakwaan' => 'Pasal 87 KUHPM tentang Desersi',
                'tanggal_kejadian' => Carbon::now()->subDays(38),
                'tempat_kejadian' => 'Yonarmed Kostrad',
                'keterangan' => 'Terdakwa masih DPO (Daftar Pencarian Orang)',
                'internal_notes' => 'Koordinasi dengan Polisi Militer untuk pencarian',
                'tags' => json_encode(['urgent', 'dpo', 'desersi']),
                'is_public' => false,
                'assigned_to' => $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/009/DIV-2/XI/2024',
                'jenis_perkara' => 'Administrasi',
                'nama' => 'Kesalahan Pencatatan Aset',
                'deskripsi' => 'Kesalahan dalam pencatatan dan inventarisasi aset unit senilai 500 juta',
                'kategori_id' => $kategoris->where('nama', 'Administrasi')->first()->id ?? 2,
                'tanggal_masuk' => Carbon::now()->subDays(40),
                'tanggal_perkara' => Carbon::now()->subDays(45),
                'tanggal_selesai' => Carbon::now()->subDays(10),
                'tanggal_pendaftaran' => Carbon::now()->subDays(41),
                'klasifikasi_perkara' => 'Sedang',
                'status' => 'Selesai',
                'priority' => 'Medium',
                'progress' => 100,
                'oditur' => json_encode(['Kapten Dedi Prasetyo']),
                'terdakwa' => json_encode(['Sertu Hadi Suryanto']),
                'pasal_dakwaan' => 'Pasal 15 UU Disiplin Prajurit TNI',
                'tanggal_kejadian' => Carbon::now()->subDays(50),
                'tempat_kejadian' => 'Gudang Logistik Yonif 4 Kostrad',
                'keterangan' => 'Kasus diselesaikan dengan sanksi administratif',
                'is_public' => true,
                'assigned_to' => $users->count() > 1 ? $users->skip(1)->first()->id : $users->first()->id,
            ],
            [
                'nomor_perkara' => 'PKR/010/DIV-2/XII/2024',
                'jenis_perkara' => 'Pelanggaran Disiplin',
                'nama' => 'Tidak Memakai Atribut Lengkap',
                'deskripsi' => 'Anggota berulang kali tidak memakai atribut lengkap saat dinas',
                'kategori_id' => $kategoris->where('nama', 'Disiplin')->first()->id ?? 1,
                'tanggal_masuk' => Carbon::now()->subDays(2),
                'tanggal_perkara' => Carbon::now()->subDays(4),
                'tanggal_pendaftaran' => Carbon::now()->subDays(3),
                'klasifikasi_perkara' => 'Ringan',
                'status' => 'Proses',
                'priority' => 'Low',
                'deadline' => Carbon::now()->addDays(15),
                'progress' => 20,
                'oditur' => json_encode(['Lettu Eko Wahyudi']),
                'terdakwa' => json_encode(['Prada Muhammad Rizki']),
                'pasal_dakwaan' => 'Pasal 6 UU Disiplin Prajurit TNI',
                'tanggal_kejadian' => Carbon::now()->subDays(6),
                'tempat_kejadian' => 'Markas Yonif 3 Kostrad',
                'keterangan' => 'Pemeriksaan awal sedang dilakukan',
                'is_public' => true,
                'assigned_to' => $users->first()->id,
            ],
        ];

        foreach ($perkaras as $perkaraData) {
            $perkara = Perkara::create($perkaraData);

            // Attach random personels with roles
            if ($personels->isNotEmpty()) {
                $randomPersonels = $personels->random(min(2, $personels->count()));
                foreach ($randomPersonels as $personel) {
                    $perkara->personels()->attach($personel->id, [
                        'peran' => collect(['Saksi', 'Terdakwa', 'Oditur', 'Penyidik'])->random()
                    ]);
                }
            }
        }

        $this->command->info('✅ Complete Perkara seeder executed successfully!');
    }
}
